insert into hospital_wards(ward_id, ward_name) values (1, 'Parker-Walter');
insert into hospital_wards (ward_id, ward_name) values (2, 'Reynolds and Sons');
insert into hospital_wards (ward_id, ward_name) values (3, 'Greenfelder and Sons');
insert into hospital_wards (ward_id, ward_name) values (4, 'Watsica Inc');
insert into hospital_wards (ward_id, ward_name) values (5, 'Luettgen Group');
insert into hospital_wards (ward_id, ward_name) values (6, 'Ferry-Kshlerin');
insert into hospital_wards (ward_id, ward_name) values (7, 'Hackett and Sons');
insert into hospital_wards (ward_id, ward_name) values (8, 'Bernhard-Welch');
insert into hospital_wards (ward_id, ward_name) values (9, 'Welch and Sons');
insert into hospital_wards (ward_id, ward_name) values (10, 'Larson Group');
insert into hospital_wards (ward_id, ward_name) values (11, 'Schuster-Hartmann');
insert into hospital_wards (ward_id, ward_name) values (12, 'Flatley Inc');
insert into hospital_wards (ward_id, ward_name) values (13, 'Bailey Inc');
insert into hospital_wards (ward_id, ward_name) values (14, 'Nitzsche Group');
insert into hospital_wards (ward_id, ward_name) values (15, 'Kutch-Weimann');
insert into hospital_wards (ward_id, ward_name) values (16, 'Collins LLC');
insert into hospital_wards (ward_id, ward_name) values (17, 'Jones, Larkin and Jacobs');
insert into hospital_wards (ward_id, ward_name) values (18, 'Jacobi-Casper');
insert into hospital_wards (ward_id, ward_name) values (19, 'Glover LLC');
insert into hospital_wards (ward_id, ward_name) values (20, 'Hermann-Grant');
insert into hospital_wards (ward_id, ward_name) values (21, 'Larkin-Boyle');
insert into hospital_wards (ward_id, ward_name) values (22, 'Raynor Inc');
insert into hospital_wards (ward_id, ward_name) values (23, 'Cormier and Sons');
insert into hospital_wards (ward_id, ward_name) values (24, 'Hirthe-Mante');
insert into hospital_wards (ward_id, ward_name) values (25, 'Streich LLC');
insert into hospital_wards (ward_id, ward_name) values (26, 'Thiel, Kuhn and Greenfelder');
insert into hospital_wards (ward_id, ward_name) values (27, 'Zboncak-Schimmel');
insert into hospital_wards (ward_id, ward_name) values (28, 'Flatley-Armstrong');
insert into hospital_wards (ward_id, ward_name) values (29, 'Reilly-Ankunding');
insert into hospital_wards (ward_id, ward_name) values (30, 'Davis, Towne and Price');